Insert into sabor(id,nombre)values(1,'Menta');
Insert into sabor(id,nombre)values(2,'Fresa');
Insert into sabor(id,nombre)values(3,'Lima');
Insert into sabor(id,nombre)values(4,'Naranja');
Insert into sabor(id,nombre)values(5,'Melocoton');
Insert into sabor(id,nombre)values(6,'Patilla');
Insert into sabor(id,nombre)values(7,'Manzana');
Insert into sabor(id,nombre)values(8,'Eucalipto');
Insert into sabor(id,nombre)values(9,'Limon');
Insert into sabor(id,nombre)values(10,'Melisa');
Insert into sabor(id,nombre)values(11,'Limon fresh');
Insert into sabor(id,nombre)values(12,'Piña');
Insert into sabor(id,nombre)values(13,'Cereza');
Insert into sabor(id,nombre)values(14,'Choco tradicional');
Insert into sabor(id,nombre)values(15,'Cafe expresso');
Insert into sabor(id,nombre)values(16,'Capuccino');
Insert into sabor(id,nombre)values(17,'Fresa con nata');
Insert into sabor(id,nombre)values(18,'Nata');
Insert into sabor(id,nombre)values(19,'Mousse de limon');
Insert into sabor(id,nombre)values(20,'Fresa picante');
Insert into sabor(id,nombre)values(21,'Miel');