Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(1,'Chupeta Rimbombin',35,'Deliciosa chupeta rellena envolvuelta con la forma de margarita','Chupeta');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(2,'Ricolin',20,'Caramelo de bolsillo que posee un sabor clasico mentolado y citrico','Caramelo duro');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(3,'Firi Firi',20,'Pastillas que proporcionan frescura al instante','Caramelo duro');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(4,'Chupeta de Corazon',30,'La tipica chupeta de fresa con forma de corazon','Chupeta');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(5,'Pirulitos',30,'Caramelos blandos y alargados','Caramelo blando');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(6,'Ricura',25,'Bola de caramelo con centro de chicle','Caramelo blando');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(7,'Original',25,'El caramelo balsamico de Candy UCAB','Caramelo blando');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(8,'Dulcin',20,'Caramelos masticables de forma cuadrada','Caramelo blando');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(9,'Choco Candy',40,'Caramelos de chocolate','Caramelo duro');
Insert into producto(id,nombre,precio,descripcion,fk_tprod)Values(10,'Blue',40,'Caramelos artesanal','Caramelo duro');
