Insert into sabor(id,nombre)values(
  1,'Menta'),
(2,'Fresa'),
(3,'Lima'),
(4,'Naranja'),
(5,'Melocoton'),
(6,'Patilla'),
(7,'Manzana'),
(8,'Eucalipto'),
(9,'Limon'),
(10,'Melisa'),
(11,'Limon fresh'),
(12,'Piña'),
(13,'Cereza'),
(14,'Choco tradicional'),
(15,'Cafe expresso'),
(16,'Capuccino'),
(17,'Fresa con nata'),
(18,'Nata'),
(19,'Mousse de limon'),
(20,'Fresa picante'),
(21,'Miel');
